// Traduction française fine des valeurs de AVATAR_VOCAB pour l'affichage.
// Les valeurs techniques (clés) restent inchangées en base ; seul le texte affiché est francisé.

export const VOCAB_LABELS = {
  gender: {
    woman: "Femme",
    man: "Homme",
    person: "Non précisé",
  },
  age_range: {
    "18-25": "18–25 ans",
    "25-35": "25–35 ans",
    "35-45": "35–45 ans",
    "45-55": "45–55 ans",
    "55-65": "55–65 ans",
    "65-75": "65–75 ans",
    "75-85": "75–85 ans",
  },
  skin_tone: {
    fair: "Très clair",
    light: "Clair",
    medium: "Médian",
    olive: "Olive",
    tan: "Hâlé",
    medium_dark: "Mat",
    dark: "Foncé",
    deep: "Très foncé",
  },
  hair_type: {
    straight: "Lisses",
    wavy: "Ondulés",
    curly: "Bouclés",
    coily: "Crépus",
  },
  hair_color: {
    black: "Noir",
    dark_brown: "Châtain foncé",
    brown: "Brun",
    light_brown: "Châtain clair",
    blonde: "Blond",
    red: "Roux",
    auburn: "Auburn",
    gray: "Gris",
    white: "Blanc",
  },
  hair_length: {
    very_short: "Très courts",
    short: "Courts",
    shoulder: "Mi-longs (épaules)",
    medium: "Mi-longs",
    long: "Longs",
  },
  hair_volume: {
    fine: "Fins",
    natural: "Naturels",
    light: "Légers",
    thick: "Épais",
  },
  hair_style: {
    clean_cut: "Coupe nette",
    tousled: "Décoiffés",
    side_parted: "Raie de côté",
    loose: "Détachés",
    softly_tied: "Attachés souples",
    half_up: "Demi-queue",
    natural_waves: "Vagues naturelles",
    bun: "Chignon",
    braided_simple: "Tresse simple",
    cornrows: "Tresses collées (cornrows)",
    box_braids: "Tresses longues (box braids)",
    braided_updo: "Tresses relevées",
  },
  nose: {
    straight: "Droit",
    aquiline: "Aquilin",
    rounded: "Arrondi",
    wide: "Large",
    narrow: "Fin",
    flat_bridge: "Arête basse",
    upturned: "Retroussé",
  },
  face_shape: {
    oval: "Ovale",
    round: "Rond",
    square_soft: "Carré adouci",
    heart: "Cœur",
    long: "Allongé",
  },
  eye_shape: {
    almond: "En amande",
    round: "Ronds",
    soft: "Doux",
    narrow: "Étirés",
    hooded: "Paupières tombantes",
    tired: "Fatigués",
    deep_set: "Enfoncés",
  },
  eye_color: {
    brown: "Marron",
    dark_brown: "Marron foncé",
    hazel: "Noisette",
    green: "Verts",
    blue: "Bleus",
    gray: "Gris",
  },
  facial_features: {
    subtle_age_lines: "Légères rides d'expression",
    gentle_wrinkles: "Rides douces",
    light_freckles: "Quelques taches de rousseur",
    soft_dimples: "Fossettes discrètes",
    expressive_brows: "Sourcils expressifs",
  },
  clothing_style: {
    casual_modest: "Sobre du quotidien",
    simple_layered: "Couches simples",
    practical_warm: "Pratique et chaud",
    classic_simple: "Classique épuré",
    soft_cardigan: "Gilet doux",
    modest_warm: "Modeste et chaleureux",
  },
  clothing_color_palette: {
    warm_earth: "Terres chaudes",
    muted_neutral: "Neutres tamisés",
    soft_jewel: "Pierres précieuses douces",
    sand_ivory: "Sable et ivoire",
    dusty_blue: "Bleu poussiéreux",
  },
  expression: {
    gentle_smile: "Sourire doux",
    hopeful: "Empli d'espoir",
    calm: "Calme",
    discreet_smile: "Sourire discret",
    tired_but_warm: "Fatigué mais chaleureux",
    resilient: "Résilient",
    serious_soft: "Sérieux et doux",
    thoughtful: "Songeur",
    pensive: "Pensif",
    reserved: "Réservé",
  },
  posture: {
    upright_calm: "Debout, posé",
    leaning_slightly: "Légèrement penché",
    relaxed: "Détendu",
    protective: "Protecteur",
    seated_dignified: "Assis, digne",
  },
  parent_energy: {
    none: "Sans objet",
    protective_parent: "Parent protecteur",
    practical_parent: "Parent pragmatique",
    tired_but_warm_parent: "Parent fatigué mais chaleureux",
  },
  cultural_style: {
    neutral_european: "Européen neutre",
    soft_modern: "Moderne sobre",
    subtle_mediterranean: "Méditerranéen subtil",
    subtle_west_african: "Afrique de l'Ouest, subtil",
    subtle_central_african: "Afrique centrale, subtil",
  },
  beard: {
    none: "Aucune",
    light: "Légère",
    full: "Fournie",
    grey: "Grisonnante",
    religious_long: "Religieuse (longue)",
  },
  moustache: {
    none: "Aucune",
    light: "Fine",
    full: "Fournie",
  },
  hair_recession: {
    none: "Aucun",
    light: "Léger",
    moderate: "Modéré",
    strong: "Marqué",
  },
  head_covering: {
    none: "Aucun",
    light_scarf: "Foulard léger (épaules)",
    headscarf: "Foulard (cheveux partiellement couverts)",
    hijab_full: "Hijab (cheveux et cou entièrement couverts)",
    taqiyah: "Taqiyah (calotte)",
    turban: "Turban",
    kippah: "Kippa",
  },
  forehead_mark: {
    none: "Aucun",
    bindi_red: "Bindi rouge",
    bindi_black: "Bindi noir",
    bindi_decorative: "Bindi décoratif",
  },
  mobility_aid: {
    none: "Aucune",
    wheelchair_manual: "Fauteuil manuel",
    wheelchair_electric: "Fauteuil électrique",
    cane: "Canne",
    crutches: "Béquilles",
    walker: "Déambulateur",
    visible_bandage: "Bandage visible",
    arm_sling: "Bras en écharpe",
    oxygen_cannula: "Lunettes à oxygène",
  },
  body_type: {
    very_thin: "Très mince",
    thin: "Mince",
    average: "Corpulence moyenne",
    chubby: "Légèrement enveloppée",
    heavy: "Forte corpulence",
  },
  workflow_status: {

    draft: "Brouillon",
    generated: "Généré",
    approved: "Approuvé",
    locked: "Verrouillé",
  },
} as const;

export type VocabKey = keyof typeof VOCAB_LABELS;

/** Renvoie une fonction de traduction pour un vocabulaire donné. */
export function labelFor(vocab: VocabKey): (value: string) => string {
  const dict = VOCAB_LABELS[vocab] as Record<string, string>;
  return (v: string) => dict?.[v] ?? v;
}
